-- Add status column to book_templates to prevent selection of templates
-- that are still being generated by the AI pipeline.
ALTER TABLE book_templates
  ADD COLUMN status text NOT NULL DEFAULT 'ready';

-- Constraint: only valid statuses
ALTER TABLE book_templates
  ADD CONSTRAINT chk_book_template_status
  CHECK (status IN ('generating', 'ready', 'failed'));

-- All existing templates are considered ready
